global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["demo-server-1:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["demo-server-1:9100"]
      - targets: ["demo-server-2:9100"]
      - targets: ["demo-server-3:9100"]
